config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"

  get  "users/logout"  => "users#logout"
  get  "brands/index"  => "brands#index"

  resources :users, only: [:index, :show, :edit, :update, :new] do
    resources :card, only: [:index, :new, :create, :destroy]
  end

  resources :products do
    resources :page_comments, only: [:create, :destroy]
    get   "buy"        => "products#buy"
    post  "buy"        => "products#pay", as: 'pay'
    get   "completion" => "products#completion"
  end

end

app/views/share/_breadcrumb.html.haml
.gretel
  .gretel-item
    = breadcrumbs separator: ' <i class="fas fa-angle-right"></i> '

app/views/share/_exhibit_btn.html.haml
- if user_signed_in?
  = link_to new_product_path, class: 'exhibit_btn' do
    = fa_icon "circle", class: 'exhibit_btn__circle'
    .exhibit_btn__text
      出品
    = fa_icon "camera", class: 'exhibit_btn__camera'
- else
  = link_to new_user_session_path, class: 'exhibit_btn' do
    = fa_icon "circle", class: 'exhibit_btn__circle'
    .exhibit_btn__text
      出品
    = fa_icon "camera", class: 'exhibit_btn__camera'

app/views/share/_footer.html.haml
.footer
  .bottom_banner{ style: "background-image: url('https://www.mercari.com/jp/assets/img/common/jp/top/download_bg_pc.jpg?96275498'); background-size: cover;" }
    .bottom_banner__inner.clearfix
      .bottom_banner__inner--left
        %p.bottom_banner__inner--left__bold_text
          スマホでかんたんフリマアプリ
        %p.bottom_banner__inner--left__download_text
          今すぐ無料ダウンロード！
        .bottom_banner__inner--left__apps
          .bottom_banner__inner--left__apps--mercari
            = image_tag( 'https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?1016580576', :class => "mercari_squere" )
          .bottom_banner__inner--left__apps--app
            = image_tag( 'https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?1016580576', :class => "App" )
          .bottom_banner__inner--left__apps--google
            = image_tag( 'https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1016580576', :class => "google" )
      .bottom_banner__inner--right
        = image_tag( 'https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?1016580576', :class => "bottom_phone" )
  .footer_text
    .bottom_links.clearfix
      .bottom_links__block
        .bottom_links__block__title
          メルカリについて
        .bottom_links__block__cell
          %span.footer_border
            会社概要（運営会社）
        .bottom_links__block__cell
          %span.footer_border
            プライバシーポリシー
        .bottom_links__block__cell
          %span.footer_border
            メルカリ利用規約
        .bottom_links__block__cell
          %span.footer_border
            メルカリ利用規約・有償ポイントに関する特約
        .bottom_links__block__cell
          %span.footer_border
            あんしんスマホサポート制度に関する利用規約
        .bottom_links__block__cell
          %span.footer_border
            コンプライアンスポリシー
        .bottom_links__block__cell
          %span.footer_border
            個人データのあんしん管理に係る基本方針
        .bottom_links__block__cell
          %span.footer_border
            特定商取引に関する表記
        .bottom_links__block__cell
          %span.footer_border
            資金決済法に基づく表示
        .bottom_links__block__cell
          %span.footer_border
            法令遵守と犯罪抑止のために
        .bottom_links__block__cell
          %span.footer_border
            採用情報
      .bottom_links__block
        .bottom_links__block__title
          メルカリを見る
        .bottom_links__block__cell
          %span.footer_border
            カテゴリー一覧
        .bottom_links__block__cell
          %span.footer_border
            ブランド一覧
        .bottom_links__block__cell
          %span.footer_border
            出品地域一覧
        .bottom_links__block__cell
          %span.footer_border
            公式ブログ
        .bottom_links__block__cell
          %span.footer_border
            公式Twitter
        .bottom_links__block__cell
          %span.footer_border
            公式Facebook
      .bottom_links__block
        .bottom_links__block__title
          ヘルプ&ガイド
        .bottom_links__block__cell
          %span.footer_border
            メルカリガイド
        .bottom_links__block__cell
          %span.footer_border
            メルカリロゴ利用ガイドライン
        .bottom_links__block__cell
          %span.footer_border
            お知らせ
        .bottom_links__block__cell
          %span.footer_border
            らくらくメルカリ便とは
        .bottom_links__block__cell
          %span.footer_border
            ゆうゆうメルカリ便とは
        .bottom_links__block__cell
          %span.footer_border
            大型らくらくメルカリ便とは
        .bottom_links__block__cell
          %span.footer_border
            車体取引ガイド
        .bottom_links__block__cell
          %span.footer_border
            返品・返金ポリシー
        .bottom_links__block__cell
          %span.footer_border
            メルカリあんしん・あんぜん宣言！
        .bottom_links__block__cell
          %span.footer_border
            偽ブランド品撲滅への取り組み
        .bottom_links__block__cell
          %span.footer_border
            メルカリボックス
      .bottom_links__block
        .bottom_links__block__title
          国
        .bottom_links__block__cell_country--foreign.clearfix
          %span.bottom_links__block__cell_country__flag
            = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?1016580576', :class => "US" )
          %span.bottom_links__block__cell_country__name
            United States
        .bottom_links__block__cell_country--foreign.clearfix
          %span.bottom_links__block__cell_country__flag
            = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?1016580576', :class => "UK" )
          %span.bottom_links__block__cell_country__name
            United Kingdam
        .bottom_links__block__cell_country.clearfix
          %span.bottom_links__block__cell_country__flag
            = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?1016580576', :class => "JP" )
          %span.bottom_links__block__cell_country__name
            日本
    .footer_mark
      = link_to root_path do
        = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?1037436093', :class => "footer_mark__top_page_link" )
      .footer_mark__mercari
        ©︎ 2018 Mercari

app/views/share/_header.html.haml
.header
  .header_top.clearfix
    .header_top__title
      = link_to root_path, class: 'header_top__title--logo' do
        = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1016580576', :class => "mercari_logo")
    .header_top__form
      .header_top__form--input-box
        = form_tag( 'search_articles_path', method: :get ) do
          = text_field_tag :q, '', class: 'header_top__form--input-box__text',placeholder: 'キーワードから探す'
          = link_to root_path, class: 'header_top__form--input-box__btn' do
            = fa_icon "search"
  .header_bottom.clearfix
    %h2.header_bottom__category_search
      カテゴリーから探す
      = render "share/header_category"
    %h2.header_bottom__brand_search
      ブランドから探す
    .header_bottom__right.clearfix
      - if user_signed_in?
        .header_bottom__right__my_page_link
          %span.header_bottom__right__my_page_link--left
            = image_tag('https://static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png')
          = link_to user_path(current_user) do
            %span.header_bottom__right__my_page_link--right
              マイページ
        .header_bottom__right__notices
          %span.header_bottom__right__notices--left
            %i.far.fa-bell
          %span.header_bottom__right__notices--right
            お知らせ
        .header_bottom__right__todo_lists
          %span.header_bottom__right__todo_lists--left
            = fa_icon "check"
          %span.header_bottom__right__todo_lists--right
            やることリスト
      - else
        = link_to "ログイン", new_user_session_path, class: 'header_bottom__right__users_index_btn'
        = link_to "新規会員登録", users_path, class: 'header_bottom__right__users_new_btn'

app/views/share/_header_category.html.haml
.header_category
  %ul
    %li
      衣服
      %ul.humans_category
        %li.human
          レディース
          %ul.clothes_content
            %li
              トップス
            %li
              パンツ
            %li
              小物
        %li.human
          メンズ
          %ul.clothes_content
            %li
              トップス
            %li
              パンツ
            %li
              小物
        %li.human
          キッズ
          %ul.clothes_content
            %li
              トップス
            %li
              パンツ
            %li
              小物
    %li
      ホビー
      %ul.hobbies_category
        %li.hobbies
          おもしろ
          %ul.hobby_content
            %li
              人形
            %li
              ラジコン
            %li
              楽器
        %li.sports
          スポーツ
          %ul.sport_content
            %li
              野球
            %li
              サッカー
            %li
              バスケ
        %li.vehicles
          乗り物
          %ul.vehicle_content
            %li
              車
            %li
              自転車
            %li
              バイク
    %li
      家電
      %ul.electronics_category
        %li.computers
          PC
          %ul.computer_content
            %li
              タブレット
            %li
              ノートパソコン
            %li
              パーツ
        %li.electronics
          生活家電
          %ul.electronic_content
            %li
              レンジ
            %li
              TV
            %li
              洗濯機
        %li.cameras
          カメラ
          %ul.camera_content
            %li
              デジカメ
            %li
              ビデオカメラ
            %li
              レンズ