config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"

  get  "users/logout"  => "users#logout"
  get  "brands/index"  => "brands#index"

  resources :users, only: [:index, :show, :edit, :update, :new] do
    resources :card, only: [:index, :new, :create, :destroy]
  end

  resources :products do
    resources :page_comments, only: [:create, :destroy]
    get   "buy"        => "products#buy"
    post  "buy"        => "products#pay", as: 'pay'
    get   "completion" => "products#completion"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :product_page_comments

  has_many :payments
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,128}+\z/i
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }
  validates :password_confirmation, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def logout

  end

  def new

  end

end

app/views/users/_footer.html.haml
%footer.single-footer
  %nav.footer-bar
    %ul.clearfix
      %li
        = link_to "プライバシーポリシー","https://www.mercari.com/jp/privacy/"
      %li
        = link_to "メルカリ利用規約","https://www.mercari.com/jp/tos/"
      %li
        = link_to "特定商取引に関する表記","https://www.mercari.com/jp/tokutei/"
  = link_to root_path, class: 'single-footer-logo' do
    = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?1016580576", alt: "mercari", height: "65", width: "80")
  %p
    %small © 2018 Mercari

app/views/users/_header.html.haml
%h1.single-head--center
  = link_to root_path do
    = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1016580576", alt: "mercari" )

app/views/users/_sidebar.html.haml
.mypage-left
  %ul.mypage-list.clearfix
    = link_to user_path(current_user), class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          マイページ
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          お知らせ
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          やることリスト
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          いいね！一覧
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          出品する
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          出品した商品-出品中
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          出品した商品-取引中
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          出品した商品-売却済み
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          購入した商品-取引中
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          購入した商品-過去の取引
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          ニュース一覧
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          評価一覧
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          ガイド
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          お問い合わせ
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    %h3.mypage-head
      売上・ポイント

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          売上・振込申請
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          ポイント
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    %h3.mypage-head
      設定

    = link_to edit_user_path(current_user), class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          プロフィール
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          住所変更
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to user_card_index_path(current_user), class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          支払い方法
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          メール/パスワード
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to new_user_path(current_user), class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          本人情報
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to root_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          電話番号の確認
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

    = link_to users_logout_path, class: 'mypage-list__link' do
      %li.mypage-list__link__item.clearfix
        .mypage-list__link__item__text
          ログアウト
        = fa_icon 'angle-right', class: 'mypage-list__link__item__icon'

app/views/users/edit.html.haml
.wrapper
  = render partial: "share/header"
- breadcrumb :users
= render "share/breadcrumb"
.main
  .mypage
    = render "sidebar"

    .mypage-right
      .mypage-user-icon
        = link_to root_path, class: 'mypage-user-icon__link' do
          .mypage-user-icon-image
          .mypage-user-icon-name
            = current_user.name
          .mypage-number
            評価 ０   出品数 ０

= render partial: "share/footer"
= link_to '出品', class: 'exhibit_btn' do
  = fa_icon "circle"
  .exhibit_btn__text
    出品
  = fa_icon "camera"

app/views/users/index.html.haml
#account-page.account-page
  .account-page__inner
    = render "header"
    .signin-page__inner--center
      .account-page__inner--center
        %h2.secound-head 新規会員登録
        .account-page__inner--right.user-form
        .login-form-inner-index
          = link_to new_user_registration_path do
            = button_tag id: "mail-login", class: "btn-custum btn-sns btn-mail" do
              %i.far.fa-envelope{ style: "font-size: 20px;" }
              メールアドレスで登録
          = link_to  do
            = button_tag id: "facebook-login", class: "btn-custum btn-sns btn-sns-facebook" do
              %i.fab.fa-facebook.custum{ style: "font-size: 20px;" }
              Facebookで登録
          = link_to  do
            = button_tag id: "google-login", class: "btn-custum btn-sns btn-sns-google" do
              %i.fab.fa-google-plus-g.custum{ style: "font-size: 20px;" }
              Google登録
    = render "footer"

app/views/users/logout.html.haml
.wrapper
  = render partial: "share/header"
- breadcrumb :users_logout
= render "share/breadcrumb"
.main
  .mypage
    = render "sidebar"

    .logout
      .logout-content
        = link_to destroy_user_session_path, method: :delete do
          .logout-content-button
            ログアウト

= render partial: "share/footer"
= link_to '出品', class: 'exhibit_btn' do
  = fa_icon "circle"
  .exhibit_btn__text
    出品
  = fa_icon "camera"

app/views/users/new.html.haml
.wrapper
  %body
    .main-contents
      .header-content
        = render partial: "share/header"
      .default-main
        .default-main-content
          .chapter-container
            %h2.chapter-container__chapter-head 本人情報の登録
            %p.chapter-container__text-center お客さまのあんしん・あんぜんな取引のため、本人情報のご登録をお願いしております。
            .chapter-single-inner
              .form-group
                %label 住所
                %span.form-default-content 必須
                .address-info
                  %address
                    %p 〒111-0000
                    %p.add-main 京都府京都市上京区智恵光院通り芦山寺上る西入る西社町198-1
                    %p.add-main 大東漆木工
                  %a 編集
                .clearfix
              .form-group.form-group-select
                %label 生年月日
                %span.form-default-content 必須
                %br
                .birthday-select-wrap
                  .select-wrap
                    = select_tag 'selectyear', options_for_select([["--","0"],["1983","1"], ["1984","2"], ["1985","3"], ["1986","4"], ["1987","5"], ["1988","6"], ["1989","7"], ["1990","8"], ["1991","9"], ["1992","10"], ["1993","11"], ["1994","12"], ["1995","13"], ["1996","14"], ["1997","15"], ["1998","16"], ["1999","17"], ["2000","18"], ["2001","19"], ["2002","20"], ["2003","21"], ["2004","22"], ["2005","23"], ["2006","24"], ["2007","25"], ["2008","26"], ["2009","27"], ["2010","28"], ["2011","29"], ["2012","30"], ["2013","31"], ["2014","32"], ["2015","33"], ["2016","34"], ["2017","35"], ["2018","36"]], selected: "0")
                    .i.fas.fa-angle-down
                  %span 年
                .birthday-select-wrap
                  .select-wrap.select-wrap__month
                    = select_tag 'selectyear', options_for_select([["--","0"],["1","1"], ["2","2"], ["3","3"], ["4","4"], ["5","5"], ["6","6"], ["7","7"], ["8","8"], ["9","9"], ["10","10"], ["11","11"], ["12","12"]], selected: "0")
                    .i.fas.fa-angle-down
                  %span 月
                .birthday-select-wrap
                  .select-wrap.select-wrap__day
                    = select_tag 'selectyear', options_for_select([["--","0"],["1","1"], ["2","2"], ["3","3"], ["4","4"], ["5","5"], ["6","6"], ["7","7"], ["8","8"], ["9","9"], ["10","10"], ["11","11"], ["12","12"], ["13","13"], ["14","14"], ["15","15"], ["16","16"], ["17","17"], ["18","18"], ["19","19"], ["20","20"], ["21","21"], ["22","22"], ["23","23"], ["24","24"], ["25","25"], ["26","26"], ["27","27"], ["28","28"], ["29","29"], ["30","30"], ["31","31"]], selected: "0")
                    .i.fas.fa-angle-down
                  %span 日
                %p.form-info.text ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
                .clearfix
              .btn-default.btn-red 登録する
              .form-group.text-right
                %p
                  = link_to "/products/new", class: "text-right-bt" do
                    本人情報の登録について
                    %i.fas.fa-angle-right
        .dedault-main-side
          = render partial: "users/sidebar"
    = render partial: "share/footer"
    = render partial: "share/exhibit_btn"

app/views/users/personal.html.haml
.wrapper
  %body
    .main-contents
      .header-content
        = render partial: "share/header"
      .default-main
        .default-main-content
          .chapter-container
            %h2.chapter-container__chapter-head 本人情報の登録
            %p.chapter-container__text-center お客さまのあんしん・あんぜんな取引のため、本人情報のご登録をお願いしております。
            .chapter-single-inner
              .form-group
                %label 住所
                %span.form-default-content 必須
                .address-info
                  %address
                    %p 〒111-0000
                    %p.add-main 京都府京都市上京区智恵光院通り芦山寺上る西入る西社町198-1
                    %p.add-main 大東漆木工
                  %a 編集
                .clearfix
              .form-group.form-group-select
                %label 生年月日
                %span.form-default-content 必須
                %br
                .birthday-select-wrap
                  .select-wrap
                    = select_tag 'selectyear', options_for_select([["--","0"],["1983","1"], ["1984","2"], ["1985","3"], ["1986","4"], ["1987","5"], ["1988","6"], ["1989","7"], ["1990","8"], ["1991","9"], ["1992","10"], ["1993","11"], ["1994","12"], ["1995","13"], ["1996","14"], ["1997","15"], ["1998","16"], ["1999","17"], ["2000","18"], ["2001","19"], ["2002","20"], ["2003","21"], ["2004","22"], ["2005","23"], ["2006","24"], ["2007","25"], ["2008","26"], ["2009","27"], ["2010","28"], ["2011","29"], ["2012","30"], ["2013","31"], ["2014","32"], ["2015","33"], ["2016","34"], ["2017","35"], ["2018","36"]], selected: "0")
                    .i.fas.fa-angle-down
                  %span 年
                .birthday-select-wrap
                  .select-wrap.select-wrap__month
                    = select_tag 'selectyear', options_for_select([["--","0"],["1","1"], ["2","2"], ["3","3"], ["4","4"], ["5","5"], ["6","6"], ["7","7"], ["8","8"], ["9","9"], ["10","10"], ["11","11"], ["12","12"]], selected: "0")
                    .i.fas.fa-angle-down
                  %span 月
                .birthday-select-wrap
                  .select-wrap.select-wrap__day
                    = select_tag 'selectyear', options_for_select([["--","0"],["1","1"], ["2","2"], ["3","3"], ["4","4"], ["5","5"], ["6","6"], ["7","7"], ["8","8"], ["9","9"], ["10","10"], ["11","11"], ["12","12"], ["13","13"], ["14","14"], ["15","15"], ["16","16"], ["17","17"], ["18","18"], ["19","19"], ["20","20"], ["21","21"], ["22","22"], ["23","23"], ["24","24"], ["25","25"], ["26","26"], ["27","27"], ["28","28"], ["29","29"], ["30","30"], ["31","31"]], selected: "0")
                    .i.fas.fa-angle-down
                  %span 日
                %p.form-info.text ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
                .clearfix
              .btn-default.btn-red 登録する
              .form-group.text-right
                %p
                  = link_to "/products/new", class: "text-right-bt" do
                    本人情報の登録について
                    %i.fas.fa-angle-right
        .dedault-main-side
          = render partial: "users/sidebar"
    = render partial: "share/footer"
    = render partial: "share/exhibit_btn"

app/views/users/show.html.haml
.wrapper
  = render partial: "share/header"
- breadcrumb :users
= render "share/breadcrumb"
.main
  .mypage
    = render "sidebar"

    .mypage-right
      .mypage-user-icon
        = link_to root_path, class: 'mypage-user-icon__link' do
          .mypage-user-icon-image
          .mypage-user-icon-name
            = current_user.name
          .mypage-number
            評価 ０   出品数 ０

      .mypage-tab-container
        %ul.mypage-tabs
          %li やることリスト
          %li__active お知らせ
        .mypage-item-list
          %ul.mypage-tab-todo

            %li.mypage-item
              現在、お知らせはありません

      .mypage-tab-container-second
        %h2.mypage-tab-head
          購入した商品
        %ul.mypage-tabs
          %li 過去の取引
          %li__active 取引中
        .mypage-item-list
          %ul.mypage-tab-todo
            %li.mypage-item
              取引中の商品がありません
= render partial: "share/footer"
= render partial: "share/exhibit_btn"