config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"

  get  "users/logout"  => "users#logout"
  get  "brands/index"  => "brands#index"

  resources :users, only: [:index, :show, :edit, :update, :new] do
    resources :card, only: [:index, :new, :create, :destroy]
  end

  resources :products do
    resources :page_comments, only: [:create, :destroy]
    get   "buy"        => "products#buy"
    post  "buy"        => "products#pay", as: 'pay'
    get   "completion" => "products#completion"
  end

end

app/controllers/card_controller.rb
class CardController < ApplicationController

include Card

  def index
    @payment = Payment.find_by(user_id: current_user.id)
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    @mycard = Payjp::Customer.retrieve(current_user.payments.first.payjp_customer_id).cards.data[0] if current_user.payments.present?
  end

  def new

  end

  def create
    unless current_user.payments.present?
      customer_id = create_customer
      @payment = Payment.find_or_initialize_by(user_id: current_user.id)
      @payment.payjp_customer_id = customer_id

      if @payment.save
        redirect_to user_path(current_user.id)
      else
        render :new
      end
    else
      render :index
    end

  end

  def destroy
    @payment = Payment.find_by(user_id: current_user.id)
    @payment.destroy
    redirect_to user_path(current_user.id)
  end

  private
  def payment_params
    params.permit(:payment).permit(:user_id, :customer_id)
  end

end

app/controllers/concerns/card.rb
module Card
  extend ActiveSupport::Concern

  def create_customer
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    year = "20" + params[:exp_year]
    token = Payjp::Token.create({
      card: {
        number: params[:number],
        cvc: params[:cvc],
        exp_month: params[:exp_month],
        exp_year: year,
        name: params[:name]
      }},
      {
        'X-Payjp-Direct-Token-Generate': 'true'
      }
    )
    Payjp::Customer.create(card: token.id).id
  end

end

app/views/card/index.html.haml
.wrapper
  .main-contents-top
    .header-content-center
      = render partial: "share/header"
    #bread-top.bread-top-top
      - breadcrumb :users_card
      = render "share/breadcrumb"
    .main-category
      .default-main-top.clearfix
        .default-main-content-right
          .chapter-containers
            %h2.chapter-containers__chapter-head 支払い方法
            .chapter-single
              %section.single-inner
                .chapter-single-content
                  %h3.chapter-sub-head クレジットカード一覧
                  - if @mycard.present?
                    %p.card= "************" + @mycard.last4
                    %p.card= @mycard.exp_month.to_s + " / " + @mycard.exp_year.to_s[2, 2]
                    %p.card= @mycard.brand
                    = link_to "/users/#{@payment.user_id}/card/#{@payment.id}", class: "delete-mycard", method: :delete do
                      %p.delete 削除する

                %ul.settings-payment-list
              %section.settings-add-card
                .chapter-single-content
                - unless @mycard.present?
                  = link_to new_user_card_path, class: "btn-defaults btn-reds submits-button" do
                    %i.far.fa-credit-card
                    クレジットカードを追加する
              .form-group.text-right
                %p
                  = link_to new_product_path, class: "text-right-bt" do
                    支払い方法について
                    %i.fas.fa-angle-right
        .defaults-main-sidetop
          = render partial: "users/sidebar"
  = render partial: "share/footer"
  = render partial: "share/exhibit_btn"

app/views/card/new.html.haml
.wrapper
  .main-contenttop
    .headcontent-center
      = render partial: "share/header"
    .bread-top-center
      - breadcrumb :users_card_new
      = render "share/breadcrumb"
    .main-categorys
      .defaults-main-content.clearfix
        .defaults-main-content-right
          .chapter-containers2
            %h2.chapter-containers2__chapter-top クレジットカード情報入力
            #add-card-form.l-single-inner
              .l-single-content
                .form-groups
                  %label カード番号
                  %span.form-require-1 必須
                  = form_with model: @payment, url: "/users/#{current_user.id}/card",  method: "POST", local: true do |f|
                    = f.text_field :number, id: "payment_card_no", class: "input-default", maxlength: "16", placeholder: "半角数字のみ"
                    %ul#card-no-error-wrapper.has-error-text
                    %ul.signup-card-list
                      %li
                        = image_tag "visa.svg", size: "49x20"
                      %li
                        = image_tag "master-card.svg", size: "49x20"
                      %li
                        = image_tag "saison-card.svg", size: "49x20"
                      %li
                        = image_tag "jcb.svg", size: "49x20"
                      %li
                        = image_tag "dinersclub.svg", size: "49x20"
                      %li.image4
                        = image_tag "discover.svg", size: "49x20"
                    .form-groups.signup-form-expire
                      %label 有効期限
                      %span.form-require-1 必須
                      %br
                      .select-wrap-1
                        = f.select :exp_month, options_for_select([["1","1"], ["2","2"], ["3","3"], ["4","4"], ["5","5"], ["6","6"], ["7","7"], ["8","8"], ["9","9"], ["10","10"], ["11","11"], ["12","12"]], selected: "0")
                        %i.fas.fa-angle-down
                      %span 月
                      %ul#expire-error-wrapper.has-error-text
                      .select-wrap-1
                        = f.select 'exp_year', options_for_select([["18","18"], ["19","19"], ["20","20"], ["21","21"], ["22","22"], ["23","23"], ["24","24"], ["25","25"], ["26","26"], ["27","27"], ["28","28"]], selected: "0"), class: "payment-card-expire"
                        %i.fas.fa-angle-down
                      %span 年
                      %ul#expire-error-wrapper.has-error-text
                    .form-groups
                      %label セキュリティーコード
                      %span.form-require-1 必須
                      = f.password_field :cvc, autocomplete: "off", id: "payment_card_security_code", class: "input-default", placeholder: "カード背面4桁もしくは3桁の番号"
                      %ul#expire-error-wrapper.has-error-text
                      .signup-seqcode
                        .signup-seqcode-text
                          %i.fas.fa-question-circle
                          %p カード裏面の番号とは?
                        .signup-seqcode-info
                    %p#primary-error.has-error-text
                    = f.submit "追加する", id: "submit-button-l", class: "btn-default-red", type: "submit"
        .defaults-main-sidetop
          = render partial: "users/sidebar"
  = render partial: "share/footer"
  = render partial: "share/exhibit_btn"