config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"

  get  "users/logout"  => "users#logout"
  get  "brands/index"  => "brands#index"

  resources :users, only: [:index, :show, :edit, :update, :new] do
    resources :card, only: [:index, :new, :create, :destroy]
  end

  resources :products do
    resources :page_comments, only: [:create, :destroy]
    get   "buy"        => "products#buy"
    post  "buy"        => "products#pay", as: 'pay'
    get   "completion" => "products#completion"
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :user
  has_many :images,                dependent: :destroy
  has_many :product_sizes,         dependent: :destroy
  has_many :product_brands,        dependent: :destroy
  has_many :product_categories,    dependent: :destroy
  has_many :product_page_comments, dependent: :destroy
  has_many :sizes,      through: :product_sizes
  has_many :brands,     through: :product_brands
  has_many :categories, through: :product_categories

  accepts_nested_attributes_for :images,             allow_destroy: true
  accepts_nested_attributes_for :product_sizes,      allow_destroy: true
  accepts_nested_attributes_for :product_brands,     allow_destroy: true
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  validates :user_id,            presence: true
  validates :images,             presence: true
  validates :name,               presence: true, length:       { maximum: 40 }
  validates :price,              presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :status,             presence: true
  validates :freight,            presence: true, numericality: { greater_than: 0 }
  validates :state_of_goods,     presence: true, numericality: { greater_than: 0 }
  validates :description,        presence: true, length:       { maximum: 1000 }
  validates :ship_method,        presence: true, numericality: { greater_than: 0 }
  validates :ship_from_location, presence: true, numericality: { greater_than: 0 }
  validates :ship_day,           presence: true, numericality: { greater_than: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
include Charge

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @category  = Category.where("id<?", 4).order("RAND()").limit(2)
    @brand     = Brand.order("RAND()").limit(2)
    @first_category_products  = Product.includes(:categories).where(categories: {id: @category[0]}).order("product_id DESC").limit(4)
    @second_category_products = Product.includes(:categories).where(categories: {id: @category[1]}).order("product_id DESC").limit(4)
    @first_brand_products  = Product.includes(:brands).where(brands: {id: @brand[0]}).order("product_id DESC").limit(4)
    @second_brand_products = Product.includes(:brands).where(brands: {id: @brand[1]}).order("product_id DESC").limit(4)
  end

  def new
    @product = Product.new
    @product.product_sizes.build
    @product.product_brands.build
    @product.product_categories.build
    @product.images.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save()
      redirect_to product_path(@product.id)
    else
      redirect_to new_product_path
    end
  end

  def show
    @other_products     = Product.order("RAND()").limit(2)
    @page_host_products = Product.where(user_id: @product.user_id)
    @page_comment       = ProductPageComment.new
    @page_comments      = @product.product_page_comments.includes(:user)
  end

  def edit
    @product_categories = @product.product_categories
  end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      redirect_to edit_product_path
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path
    else
      redirect_to product_path
    end
  end

  def buy
    @product = Product.find(params[:product_id])
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    @mycard = Payjp::Customer.retrieve(current_user.payments.first.payjp_customer_id).cards.data[0] if current_user.payments.present?
  end

  def pay
    @product = Product.find(params[:product_id])
    @payment = Payment.find_by(user_id: current_user.id)
    create_charge(@product.price, @payment.payjp_customer_id)
    @product.update(status: 1)
  end


  private

  def product_params
    params.require(:product).permit(:name, :price, :freight, :state_of_goods, :description, :ship_method, :ship_from_location, :ship_day, product_sizes_attributes:[:id, :size_id], product_brands_attributes:[:id, :brand_id], product_categories_attributes:[:id, :category_id], images_attributes:[:id, :first_image, :second_image, :third_image, :forth_image]).merge(status: 0, user_id: current_user.id)
  end


  def set_product
    @product = Product.find(params[:id])
  end

end

app/views/products/_message-creater-name.html.haml
%figure
  .message-user-unknown
    %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/user-icon.svg?1016580576"}/
  - if comment.user_id == @product.user_id && comment.text != "出品者がコメントを削除しました"
    .product-exhibit-mark
      出品者
  - else
- unless comment.text == "出品者がコメントを削除しました"
  .message-name
    = comment.user.name

app/views/products/_messages-conditions.html.haml
- num = 0
- @page_comments.each do |comment|
  - num += 1
  / 一番古いメッセージ
  - if num == 1
    .message-item-1.clearfix
      - if comment.user_id == @product.user_id
        / 持ち主
        %a.message-user-1
          = render partial: "message-creater-name", locals: { comment: comment }
        = render partial: "page-message", locals: { comment: comment }

      - else
        / その他
        %a.message-user-2
          = render partial: "message-creater-name", locals: { comment: comment }
        = render partial: "page-message", locals: { comment: comment }


  - else
    / 二つ目以降
    .message-item-2.clearfix
      - if comment.user_id == @product.user_id
        / 持ち主
        %a.message-user-1
          = render partial: "message-creater-name", locals: { comment: comment }
        = render partial: "page-message", locals: { comment: comment }

      - else
        / その他
        %a.message-user-2
          = render partial: "message-creater-name", locals: { comment: comment }
        = render partial: "page-message", locals: { comment: comment }

app/views/products/_page-message.html.haml
- if comment.user_id == @product.user_id
  .message-body-1
    - if comment.text == '出品者がコメントを削除しました'
      .message-body-height-1
        .message-body
          .message-body-text
            = comment.text
          .message-icons.clearfix
            %time.message-icon-left
              %i.far.fa-clock
              %span 13 日前
            .message-icon-right

    - else
      .message-body-height-2
        .message-body
          .message-body-text
            = comment.text
          .message-icons.clearfix
            %time.message-icon-left
              %i.far.fa-clock
              %span 13 日前
            - if current_user.id == @product.user_id
              .message-icon-right
                = link_to "/products/#{@product.id}/page_comments/#{comment.id}", method: :delete do
                  = fa_icon 'trash-alt', class: 'page-message-trash'
            - else


- else
  .message-body-2
    - if comment.text == '出品者がコメントを削除しました'
      .message-body-height-1
        .message-body
          .message-body-text
            = comment.text
          .message-icons.clearfix
            %time.message-icon-left
              %i.far.fa-clock
              %span 13 日前
            .message-icon-right
              %i.far.fa-flag

    - else
      .message-body-height-2
        .message-body
          .message-body-text
            = comment.text
          .message-icons.clearfix
            %time.message-icon-left
              %i.far.fa-clock
              %span 13 日前
            .message-icon-right
              %i.far.fa-flag
              - if current_user.id == @product.user_id
                = link_to "/products/#{@product.id}/page_comments/#{comment.id}", method: :delete do
                  = fa_icon 'trash-alt', class: 'page-message-trash'
              - else

app/views/products/_product-brands.html.haml
.brand.clearfix
  ピックアップブランド

  .brand__name
    = @brand[0].name
    新着アイテム
  .brand__items.clearfix
    - @first_brand_products.each do |product|
      = link_to product_path(product.id) do
        .brand__items--each
          .brand__items--each__img
            = image_tag product.images[0].first_image.url
            - unless product.status.to_i == 0
              .owl-sold
                .owl-sold-mark
                  .owl-sold-text
                    SOLD
          .brand__items--each__detail
            .brand__items--each__detail__top-name
              = product.name
            .brand__items--each__detail__middle.clearfix
              .brand__items--each__detail__middle--price
                ¥
                = number_with_delimiter(product.price)
              .brand__items--each__detail__middle--heart.clearfix
                .brand__items--each__detail__middle--heart__mark
                  %i.far.fa-heart.small
                .brand__items--each__detail__middle--heart__num
                  2
            .brand__items--each__detail__bottom-tax
              (税込)
  .brand__link_to_all
    全ての商品を見る


  .brand__name
    = @brand[1].name
    新着アイテム
  .brand__items.clearfix
    - @second_brand_products.each do |product|
      = link_to product_path(product.id) do
        .brand__items--each
          .brand__items--each__img
            = image_tag product.images[0].first_image.url
            - unless product.status.to_i == 0
              .owl-sold
                .owl-sold-mark
                  .owl-sold-text
                    SOLD
          .brand__items--each__detail
            .brand__items--each__detail__top-name
              = product.name
            .brand__items--each__detail__middle.clearfix
              .brand__items--each__detail__middle--price
                ¥
                = number_with_delimiter(product.price)
              .brand__items--each__detail__middle--heart.clearfix
                .brand__items--each__detail__middle--heart__mark
                  %i.far.fa-heart.small
                .brand__items--each__detail__middle--heart__num
                  2
            .brand__items--each__detail__bottom-tax
              (税込)
  .brand__link_to_all
    全ての商品を見る

app/views/products/_product-categories.html.haml
.category.clearfix
  ピックアップブランド

  .category__name
    = @category[0].name
    新着アイテム
  .category__items.clearfix
    - @first_category_products.each do |product|
      = link_to product_path(product.id) do
        .category__items--each
          .category__items--each__img
            = image_tag product.images[0].first_image.url
            - unless product.status.to_i == 0
              .owl-sold
                .owl-sold-mark
                  .owl-sold-text
                    SOLD
          .category__items--each__detail
            .category__items--each__detail__top-name
              = product.name
            .category__items--each__detail__middle.clearfix
              .category__items--each__detail__middle--price
                ¥
                = number_with_delimiter(product.price)
              .category__items--each__detail__middle--heart.clearfix
                .category__items--each__detail__middle--heart__mark
                  %i.far.fa-heart.small
                .category__items--each__detail__middle--heart__num
                  2
            .category__items--each__detail__bottom-tax
              (税込)
  .category__link_to_all
    全ての商品を見る


  .category__name
    = @category[1].name
    新着アイテム
  .category__items.clearfix
    - @second_category_products.each do |product|
      = link_to product_path(product.id) do
        .category__items--each
          .category__items--each__img
            = image_tag product.images[0].first_image.url
            - unless product.status.to_i == 0
              .owl-sold
                .owl-sold-mark
                  .owl-sold-text
                    SOLD
          .category__items--each__detail
            .category__items--each__detail__top-name
              = product.name
            .category__items--each__detail__middle.clearfix
              .category__items--each__detail__middle--price
                ¥
                = number_with_delimiter(product.price)
              .category__items--each__detail__middle--heart.clearfix
                .category__items--each__detail__middle--heart__mark
                  %i.far.fa-heart.small
                .category__items--each__detail__middle--heart__num
                  2
            .category__items--each__detail__bottom-tax
              (税込)
  .category__link_to_all
    全ての商品を見る

app/views/products/_product_categories.html.haml
.category.clearfix
  ピックアップブランド

  .category__name
    = @category[0].name
    新着アイテム
  .category__items.clearfix
    - @first_category_products.each do |product|
      = link_to product_path(product.id) do
        .category__items--each
          .category__items--each__img
            = image_tag product.images[0].first_image.url
            - unless product.status.to_i == 0
              .owl-sold
                .owl-sold-mark
                  .owl-sold-text
                    SOLD
          .category__items--each__detail
            .category__items--each__detail__top-name
              = product.name
            .category__items--each__detail__middle.clearfix
              .category__items--each__detail__middle--price
                ¥
                = number_with_delimiter(product.price)
              .category__items--each__detail__middle--heart.clearfix
                .category__items--each__detail__middle--heart__mark
                  %i.far.fa-heart.small
                .category__items--each__detail__middle--heart__num
                  2
            .category__items--each__detail__bottom-tax
              (税込)
  .category__link_to_all
    全ての商品を見る


  .category__name
    = @category[1].name
    新着アイテム
  .category__items.clearfix
    - @second_category_products.each do |product|
      = link_to product_path(product.id) do
        .category__items--each
          .category__items--each__img
            = image_tag product.images[0].first_image.url
            - unless product.status.to_i == 0
              .owl-sold
                .owl-sold-mark
                  .owl-sold-text
                    SOLD
          .category__items--each__detail
            .category__items--each__detail__top-name
              = product.name
            .category__items--each__detail__middle.clearfix
              .category__items--each__detail__middle--price
                ¥
                = number_with_delimiter(product.price)
              .category__items--each__detail__middle--heart.clearfix
                .category__items--each__detail__middle--heart__mark
                  %i.far.fa-heart.small
                .category__items--each__detail__middle--heart__num
                  2
            .category__items--each__detail__bottom-tax
              (税込)
  .category__link_to_all
    全ての商品を見る

app/views/products/_ship_from_location.html.haml
- if @product.ship_from_location.to_i == 1
  北海道
- elsif @product.ship_from_location.to_i == 2
  青森県
- elsif @product.ship_from_location.to_i == 3
  岩手県
- elsif @product.ship_from_location.to_i == 4
  宮城県
- elsif @product.ship_from_location.to_i == 5
  秋田県
- elsif @product.ship_from_location.to_i == 6
  山形県
- elsif @product.ship_from_location.to_i == 7
  福島県
- elsif @product.ship_from_location.to_i == 8
  茨城県
- elsif @product.ship_from_location.to_i == 9
  栃木県
- elsif @product.ship_from_location.to_i == 10
  群馬県
- elsif @product.ship_from_location.to_i == 11
  埼玉県
- elsif @product.ship_from_location.to_i == 12
  千葉県
- elsif @product.ship_from_location.to_i == 13
  東京都
- elsif @product.ship_from_location.to_i == 14
  神奈川県
- elsif @product.ship_from_location.to_i == 15
  新潟県
- elsif @product.ship_from_location.to_i == 16
  富山県
- elsif @product.ship_from_location.to_i == 17
  石川県
- elsif @product.ship_from_location.to_i == 18
  福井県
- elsif @product.ship_from_location.to_i == 19
  山梨県
- elsif @product.ship_from_location.to_i == 20
  長野県
- elsif @product.ship_from_location.to_i == 21
  岐阜県
- elsif @product.ship_from_location.to_i == 22
  静岡県
- elsif @product.ship_from_location.to_i == 23
  愛知県
- elsif @product.ship_from_location.to_i == 24
  三重県
- elsif @product.ship_from_location.to_i == 25
  滋賀県
- elsif @product.ship_from_location.to_i == 26
  京都府
- elsif @product.ship_from_location.to_i == 27
  大阪府
- elsif @product.ship_from_location.to_i == 28
  兵庫県
- elsif @product.ship_from_location.to_i == 29
  奈良県
- elsif @product.ship_from_location.to_i == 30
  和歌山県
- elsif @product.ship_from_location.to_i == 31
  鳥取県
- elsif @product.ship_from_location.to_i == 32
  島根県
- elsif @product.ship_from_location.to_i == 33
  岡山県
- elsif @product.ship_from_location.to_i == 34
  広島県
- elsif @product.ship_from_location.to_i == 35
  山口県
- elsif @product.ship_from_location.to_i == 36
  徳島県
- elsif @product.ship_from_location.to_i == 37
  香川県
- elsif @product.ship_from_location.to_i == 38
  愛媛県
- elsif @product.ship_from_location.to_i == 39
  高知県
- elsif @product.ship_from_location.to_i == 40
  福岡県
- elsif @product.ship_from_location.to_i == 41
  佐賀県
- elsif @product.ship_from_location.to_i == 42
  長崎県
- elsif @product.ship_from_location.to_i == 43
  熊本県
- elsif @product.ship_from_location.to_i == 44
  大分県
- elsif @product.ship_from_location.to_i == 45
  宮城県
- elsif @product.ship_from_location.to_i == 46
  鹿児島県
- elsif @product.ship_from_location.to_i == 47
  沖縄県
- else
  未定

app/views/products/buy.html.haml
.buy
  = render "users/header"
  .buy-main
    .buy-container
      .buy-head
        購入を確定しますか？
      .buy-item
        .buy-item-inner
          .buy-item-inner__image
            .img
              = image_tag @product.images[0].first_image.url
          .buy-item-inner__name
            = @product.name
          .buy-form
            .buy-price
              ¥
              = number_with_delimiter(@product.price)
              .item-shipping
                - if @product.freight == 1
                  %p.shipping-price 送料込み
                - else
                  %p.shipping-price 着払い
            .buy-accordion
              ポイントはありません
            .buy-price-table
              .buy-price-table__text
                支払い金額
              .buy-price-table__pay
                %p ¥
                = number_with_delimiter(@product.price)
          = form_with model: @product, url: product_pay_path, method: :post, local: true do |f|
            - if @mycard.present?
              = f.submit '購入する', class: 'buy-button-pay-btn'
            - else
              %p.buy-no-text
                配送先と支払い方法の入力を完了してください。
              %p.buy-button-pay-no
                購入する

      .buy-street-address
        .buy-street-address__inner
          配送先
          .buy-street-address__inner__text
            %br 〒578-0937
            %br 大阪府 東大阪市 花園本町1-1-11
            %br 小山 大輔
          = link_to new_user_path(current_user) do
            .buy-street-address__inner__change
              変更する
              = fa_icon 'angle-right'
      .buy-user-card
        .buy-user-card-content
          .buy-user-card-content__inner
            支払い方法
            .buy-user-card-content__inner__text
              - if @mycard.present?
                %br= "************" + @mycard.last4
                %br= @mycard.exp_year
                %br= @mycard.exp_month
                %br= @mycard.brand
            .buy-user-card-content__inner__image
            = link_to user_card_index_path(current_user) do
              .buy-user-card-content__inner__change
                変更する
                = fa_icon 'angle-right'
  = render "users/footer"

app/views/products/index.html.haml
.wrapper
  = render partial: "share/header"
  .top_banner{ style: "background-image: url('https://www.mercari.com/jp/assets/img/common/jp/top/main_bg_pc.jpg'); background-size: cover;" }
    .top_banner__banner_content.clearfix
      .top_banner__banner_content__left
        %p.top_banner__banner_content__left--main
          スマホでかんたん
          %br
          フリマアプリ
        %p.top_banner__banner_content__left--sub
          メルカリはスマホカメラからすぐに出品できる
          %br
          購入時も安心な独自システムのアプリです
        = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?1016580576', :class => "App" )
        = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1016580576', :class => "google" )
      .top_banner__banner_content__right
        = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?1016580576', :class => "top_phone" )
  .main.clearfix
    .pickup.clearfix
      = render partial: "product-categories"
    .pickup.clearfix
      = render partial: "product-brands"

  = render partial: "share/footer"
  = render partial: "share/exhibit_btn"

app/views/products/pay.html.haml
.done
  = render "users/header"
  .done-main
    .done-top
      .done-top__wait
        %i.far.fa-clock
        .done-top__wait__text
          発送をお待ちください
      .done-top__text
        出品者からの発送通知をお待ちください
    .done-text
      .done-text__buy
        購入が完了しました
    .done-image
      .done-image__content
      .done-image__name
        = @product.name
    .done-price
      ¥
      = number_with_delimiter(@product.price)
      .done-price__postage
        - if @product.freight == 1
          送料込み
        - else
          着払い
    .done-address
      .done-address__title
        発送先
      .done-address__content
        %br 〒578-0937
        %br 大阪府 東大阪市 花園本町1-1-11
        %br 小山 大輔
    .done-bottom
      .done-bottom__top
        発送通知後の流れ
      .done-bottom__icon
        %i.fas.fa-star.star
        %i.fas.fa-grin.smile
        %i.fas.fa-meh.meh
        %i.fas.fa-tired.bad
        %i.fas.fa-star.star
      .done-bottom__text
        %br 商品を受け取ったら
        %br 出品者の評価をしましょう。
        %br 購入代金が出品者に振り込まれます。
        %br 評価後に取引は完了です。
      .done-bottom__link
        = link_to root_path do
          マイページもどる
  = render "users/footer"

app/views/products/show.html.haml
.wrapper
  = render partial: "share/header"
- breadcrumb :products, @product
= render "share/breadcrumb"

%body
  /商品見出しから、いいね機能もここに
  .default-container
    %section.item-box-container.l-single-container
      %h1.item-name
        = @product.name

      /商品画像、詳細box
      .item-main-content.clearfix
        /商品画像部分
        .item-photo
          /メイン画像
          .owl-item
            = image_tag @product.images[0].first_image.url
            - unless @product.status.to_i == 0
              .owl-sold
                .owl-sold-mark
                  .owl-sold-text
                    SOLD

          .owl-dots.clearfix
            .owl-dot
              .owl-dot-inner
                - if @product.images[0].forth_image.url.present?
                  = image_tag @product.images[0].forth_image.url
            .owl-dot
              .owl-dot-inner
                - if @product.images[0].third_image.url.present?
                  = image_tag @product.images[0].third_image.url
            .owl-dot
              .owl-dot-inner
                - if @product.images[0].second_image.url.present?
                  = image_tag @product.images[0].second_image.url
            .owl-dot
              .owl-dot-inner
                = image_tag @product.images[0].first_image.url
              /画像、説明書きここまで

        /商品詳細
        %table.item-detail-table
          %tbody
            %tr
              %th 出品者
              %td
                %a
                  = @product.user.name
                %div
                  .item-user-ratings
                    %i.fas.fa-grin.smile
                    %span 100
                  .item-user-ratings
                    %i.fas.fa-meh.meh
                    %span 50
                  .item-user-ratings
                    %i.fas.fa-tired.bad
                    %span 0
            %tr
              %th カテゴリー
              %td
                %a
                  = @product.categories[0].name
                %a
                  .item-detail-table-sub-category
                    %i.fas.fa-angle-right.right
                    = @product.categories[1].name
                %a
                  .item-detail-table-sub-sub-category
                    %i.fas.fa-angle-right.right
                    = @product.categories[2].name
            %tr
              %th ブランド
              %td
                %a
                  - if @product.brands.exists?
                    = @product.brands[0].name
            %tr
              %th 商品の状態
              %td
                - if @product.freight.to_i == 1
                  新品、未使用
                - elsif @product.freight.to_i == 2
                  未使用に近い
                - elsif @product.freight.to_i == 3
                  目立った傷や汚れなし
                - elsif @product.freight.to_i == 4
                  やや傷や汚れあり
                - elsif @product.freight.to_i == 5
                  傷や汚れあり
                - else
                  全体的に状態が悪い
            %tr
              %th 配送料の負担
              %td
                - if @product.freight == 1
                  送料込み(出品者負担)
                - else
                  着払い(購入者負担)
            %tr
              %th 配送の方法
              %td
                - if @product.ship_method.to_i == 1
                  未定
                - elsif @product.ship_method.to_i == 2
                  らくらくメルカリ便
                - elsif @product.ship_method.to_i == 3
                  ゆうメール
                - elsif @product.ship_method.to_i == 4
                  レターパック
                - elsif @product.ship_method.to_i == 5
                  普通郵便(定形、定形外)
                - elsif @product.ship_method.to_i == 6
                  クロネコヤマト
                - elsif @product.ship_method.to_i == 7
                  ゆうパック
                - elsif @product.ship_method.to_i == 8
                  クリックポスト
                - else
                  ゆうパケット
            %tr
              %th 配送元地域
              %td
                %a
                  = render "ship_from_location"
            %tr
              %th 発送日の目安
              %td
                - if @product.ship_day.to_i == 1
                  1〜2日で発送
                - elsif @product.ship_day.to_i == 2
                  2〜3日で発送
                - else
                  4〜7日で発送

      /値段表示
      .item-price-box.text-center
        %span.item-price
          ¥
          = number_with_delimiter(@product.price)
        %span.item-tax (税込)
        %span.item-shipping-fee
          - if @product.freight.to_i == 1
            送料込み
          - else
            着払い

      - if user_signed_in?
        - unless current_user.id == @product.user_id
          - if @product.status.to_i == 0
            = link_to product_buy_path(@product.id) do
              .item-buy-btn 購入画面に進む
              .item-btn-client
          - else
            .item-buy-btn.f18-24 売り切れました
        - else
      - else
        - if @product.status.to_i == 0
          = link_to new_user_session_path do
            .item-buy-btn 購入画面に進む
        - else
          .item-buy-btn.f18-24 売り切れました

      /出品者記入項目
      .item-description.f14
        %p.item-description-inner
          = @product.description


      /いいね機能、報告url、取り組みurl
      .item-button-container.clearfix
        .item-button-left
          %a.item-button.item-button-like
            %i.far.fa-heart
            %span いいね!
            %span 1
          /不適切報告
          %a.item-button.item-button-report.clearfix
            %i.far.fa-flag
            %span 不適切な商品の報告
        /取り組みurl
        .item-button-right
          %a.description-page
            %i.fas.fa-lock
            %span あんしん・あんぜんへの取り組み

    - if user_signed_in?
      - if current_user.id == @product.user_id
        - if @product.status.to_i == 0
          .item-edit-box
            = link_to edit_product_path, class: "item-edit-box__edit-btn__btn" do
              商品の編集
            .item-edit-box__text
              or
            = button_tag class: "item-edit-box__stop-btn__btn" do
              出品を一旦停止する
            = link_to "/products/#{@product.id}", method: :delete, class: "item-edit-box__delete-btn__btn" do
              この商品を削除する
        - else
      - else

    /コメント表示（箱）
    .item-detail-message
      / コメント枠
      .message-container
        - if @page_comments.length > 0
          .message-content
            .message-items
              = render partial: "messages-conditions"
        - if user_signed_in?
          .message-submit
            .message-submit__attension
              相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
            = form_for [@product, @page_comment], url: product_page_comments_path(@product.id) do |f|
              = f.text_area :text, class: 'message-submit__text'
              - if @product.status.to_i == 0
                = f.submit 'コメントする', class: 'message-submit__confirm'
              - else
                売り切れのためコメントできません
        - else

    /別商品詳細ページリンク
    %ul.nav-item-link-prev-next.clearfix
      %li.nav-item-link-prev
        = link_to product_path(@other_products[0].id) do
          %i.fas.fa-angle-left
          = @other_products[0].name
      %li.nav-item-link-next
        = link_to product_path(@other_products[1].id) do
          = @other_products[1].name
          %i.fas.fa-angle-right.right

    /facebook,twitter,pinterest?アイコン
    .item-social-media-box
      .text-center
        .fb-save.fb_iframe_widget
      /snsリンク
      %ul.social-media-box
        %li
          %a.share-btn
            %i.fab.fa-facebook-square.custum{ style: "font-size: 44px;" }
        %li
          %a.share-btn
            %i.fab.fa-twitter-square.custum{ style: "font-size: 44px;" }
        %li.social-hidden-item
          %a
            %i.fab.fa-line.custum{ style: "font-size: 44px;" }
        %li
          %a.share-btn
            %i.fab.fa-pinterest-square.custum{ style: "font-size: 44px;" }

    - if @page_host_products.length >= 2
      .items-in-user-profile
        .items-box-head
          %a
            = @product.user.name
            さんのその他の出品
        .items-box.clearfix
          - number = 0
          - @page_host_products.each do |product|
            - unless product.id == @product.id
              - number += 1
              - if (number <= 6)
                = link_to product_path(product.id) do
                  .each-item
                    .each-item__img
                      = image_tag product.images[0].first_image.url
                      - unless product.status.to_i == 0
                        .owl-sold
                          .owl-sold-mark
                            .owl-sold-text
                              SOLD
                    .each-item__detail
                      .each-item__detail__top-name
                        = product.name
                      .each-item__detail__middle.clearfix
                        .each-item__detail__middle--price
                          ¥
                          = number_with_delimiter(product.price)
                        .each-item__detail__middle--heart.clearfix
                          .each-item__detail__middle--heart__mark
                            %i.far.fa-heart.small
                          .each-item__detail__middle--heart__num
                            2
                      .each-item__detail__bottom-tax
                        (税込)

= render partial: "share/footer"